import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='purple-dark text-foreground bg-background'>
      <body className={inter.className} >
      <Providers>
        <NavBar />
          {children}
        <Footer />
      </Providers>
      </body>
    </html>
  )
}
